# Prometheus configuration for RAG MS MARCO monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'rag-msmarco'

rule_files:
  # Add alerting rules here if needed
  # - "alerting_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # RAG API metrics
  - job_name: 'rag-api'
    static_configs:
      - targets: ['rag_api:9100']  # Assumes metrics endpoint on port 9100
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']  # Standard nginx exporter port
    scrape_interval: 30s
    scrape_timeout: 10s

  # Qdrant metrics (if exposed)
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Node exporter for system metrics (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093